Repository jenkinsci/repo-plugin, pull requests merged in 2019-11, with the labels that each got.

#53 Added support for --no-clone-bundle
  src/main/java/hudson/plugins/repo/RepoScm.java
  src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
  src/main/webapp/help-noCloneBundle.html
Labels: enhancement

#54 [JENKINS-37557] Better support for pipelines
  src/main/java/hudson/plugins/repo/ChangeLog.java
  src/main/java/hudson/plugins/repo/RepoScm.java
  src/main/resources/hudson/plugins/repo/RepoChangeLogSet/digest.jelly
  src/main/resources/hudson/plugins/repo/RepoChangeLogSet/index.jelly
Labels: bug, ui

#59 Moved documentation from wiki to GitHub repo + modern Jenkins core
  doc/README.adoc
  pom.xml
  src/test/java/hudson/plugins/repo/RepoScmTest.java
Labels: chore, dependencies, documentation
